node {
   def commit_id
   
   wrap([$class: 'BuildUser']) {
     echo "BUILD_USER that started this Pipeline: ${BUILD_USER}"
   }
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh '/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/myNodeJS/bin/npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("wardviaene/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
